---
title: "Ekspresowa analiza ryzyka:"
pest: "Helicoverpa zea"
taxoauthor: "(Boddie, 1850)"
author:
  - name: Wojciech   Kubasik
    email: plantquarantine@pra.org
    affiliationNum: A
    footnote: Autor korespondencyjny
  - name: Magdalena   Gawlak
    affiliationNum: A
  - name: Michał   Czyż
    affiliationNum: A
  - name: Agata Olejniczak
    affiliationNum: A
  - name: Tomasz Kałuski
    affiliationNum: A
address:
  - affiliationNum: A
    code: Instytut Ochrony Roślin
    address: "ul. Węgorka 20, Poznań, 60-318" 
keywords:
  - "Ocena Zagrożenia Agrofagiem"
  - "Helicoverpa zea"
date: "Październik 11, 2017^[Raport został wygenerowany w R [@rcore2018] z użyciem knitr i bookdown [@xie2015; @xie2016]]"
site: bookdown::bookdown_site
abstract: |
  `r if(knitr:::is_latex_output()) paste(readLines("abstract.md"), collapse = '\n  ')`
nocite: | 
  @billen1984, @luliang2002, @purcell1992
bibliography: [pra.bib]
link-citations: yes
geometry: margin=1in
graphics: yes
compact-title: true
always_allow_html: yes
classoption: a4paper
urlcolor: Cerulean
linkcolor: TealBlue
citecolor: TealBlue
lang: pl
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library('kableExtra')
library('magrittr')
library('dplyr')
if(knitr::is_latex_output()) {
  options(knitr.table.format = "latex")
} else {
    options(knitr.table.format = "html")
}
formatingCite <- function(x) {
  paste0('\\citeauthor{', x, '}, ', '\\hyperlink{ref-', x, '}',
                          '{\\citeyear{', x, '}}')
}
```

`r if (knitr:::is_html_output()) '# Podsumowanie {-}'`

```{r echo = F, eval = T, results = 'asis'}
if (knitr::is_html_output()) {
 obszar_PRA            <- c('Rzeczpospolita Polska')
 obszar_zagrozenia     <- c('uprawy   polowe   (głównie   kukurydzy),   przede   wszystkim   w   Polsce północno-zachodniej, w niewielkim stopniu również uprawy w warunkach chronionych w całej Polsce.')
 glowne_wnioski        <- c('*H. zea* jest gatunkiem motyla z rodziny sówkowatych (Noctuidae) szeroko rozsiedlonym w cieplejszych rejonach obu Ameryk. Gąsienice żerują polifagicznie na wielu roślinach, przynosząc wysokie straty ekonomiczne, między innymi w uprawie kukurydzy, sorgo, bawełny i pomidorów. Motyle wykazują duże zdolności migracyjne i są wstanie zasiedlać czasowo miejsca o znacznie chłodniejszym klimacie (np. północ Kanady, południe Argentyny). W obecnych warunkach klimatycznych Polski powstanie osiadłych populacji H. zea  jest bardzo mało prawdopodobne, jednak w przypadku  rozwinięcia się licznych populacji na południu Europy, terytorium naszego kraju znajdzie się w zasięgu migrujących osobników (analogiczna sytuacja ma miejsce w wypadku bliźniaczego gatunku *H. armigera*). Istnieje także ryzyko, że w przypadku zawleczenia gatunek ten może wyrządzić szkody w uprawach pod osłonami – zarówno roślin ozdobnych jak i warzyw.')
 ryzyko_ogolem         <- c('Średnie')
 srodki_fitosanitarne  <- c('')
 ryzyko_fitosanitarne  <- c('Średnie')
 niepewnosc_oceny      <- c('Średnia')
 inne_rekomendacje     <- c('<ul><li>Należy na bieżąco sprawdzać informacje o znaczących stratach wyrządzanych przez *H. armigera* i na podstawie odłowionych osobników dorosłych sprawdzać, czy nie są to przedstawiciele *H. zea*.</li></ul>')
 cat('<div class="abstract-box"><div class="title-box">Podsumowanie Analizy Ryzyka Zagrożenia Agrofagiem (Ekspres PRA) dla <i>', rmarkdown::metadata$pest, '</i></div>')
 cat('<p><b>Obszar PRA: </b>',  obszar_PRA, '</p><p><b>Opis obszaru zagrożenia: </b>', obszar_zagrozenia, '</p><p><b>Główne wnioski:</b><br>', glowne_wnioski, '</p><p><b>Ogólna ocena ryzyka: </b><span style="background-color: #f5d0b8;">', ryzyko_ogolem, '</span></p>', '<div class="rating-box"><div class="top">Ryzyko fitosanitarne</div><div class="center"<p></p>', ryzyko_fitosanitarne,'</div></div><div class="rating-box"><div class="top">Poziom niepewności oceny</div><div class="center"><p></p>', niepewnosc_oceny, '</div></div><br>
<b>Inne rekomendacje: </b>', inne_rekomendacje,'</div>')
 }
```
